### ISSUE TITLE
Loading malformed message crashes golem_message with UnboundLocalError.

### ISSUE THREAD

**Issue by rwrzesien** [golemfactory/golem-messages#121] opened 2018-02-01 15:52 UTC
```python
from golem_messages.shortcuts       import dump
from golem_messages.shortcuts       import load
from golem_messages                 import message

(CONCENT_PRIVATE_KEY,   CONCENT_PUBLIC_KEY)   = (b'<\xc4\x92X\xe6\t8\x14Q\xcd\x83\xa7]U\xe4\x0fF\x04=\xfe\xfc\x0eo\xf8_O\x94\xbf\xe1G.@',
 b'9\xf4S\xd6\xf9\xdd\xb4\x03\xd8\xa2\xa6<:S\xef_\x01X>\x05\xd1^\tW\xd7\xed\x9c\x18\xe54\x9eq \x13/\xa8\x92(\xbb5t\x17\x1e5\x13Ew\n\xff8\x0f\xbb1\x19FA\xa1\xb7\x08\x8c\xf6s\x96\x18')
(PROVIDER_PRIVATE_KEY,  PROVIDER_PUBLIC_KEY)  = (b'\xa9\xf4.\t\x04\x9a\xf3\x15\xfd9\xae\xd9\xc4\x90\xb2\x91(\xcciL\x1c\x83\xcd\xe1\x0f\x19\x9e\xb5\xefN\x0fi',
 b'8\xd6*\x12N\xa6|\xaf\x0e8\x16\xdd\xfd\x18\xf3\x9b<\x98BG\xf8/_7\xfc\xe6\xc7)\xc3\xaf{\xb3%L\xedr\xd4ei\x8b(dz!D\xf2\xe6\x07OY\x03\xca<\xa5m\xb2R5\xd3@\x1bB\xe91')
(REQUESTOR_PRIVATE_KEY, REQUESTOR_PUBLIC_KEY) = (b'\x07H\x11\xff\xfa\x98\xba5\xe9\xd8hQ>\x02\xea\xa23\x0b\xd2+D\xa0>wo\xf1\xa1;\xf8\xfd\x11\x9a',
 b'\xca\x0f\xfdvk\xc4z\x8f\xaf!\x03b8\xc2j\xf4\xd3\xb7,\x7f\x97\x99\x1a\xfc\xfa\x9c\x19\xe3\x86\xf0,\x98d\x86\x8a\xdb\xa9\xdb\xd2\xb5\xfe\xde&\x99\xea\x1d1\xaeHu\x92\xee\xb0\x02\x07\xca\xc4\xc2_\x18\xe11^t')

task_to_compute = message.TaskToCompute()
task_to_compute.compute_task_def = message.ComputeTaskDef()
task_to_compute.compute_task_def['task_id'] = 1

serialized_task_to_compute      = dump(task_to_compute,             PROVIDER_PRIVATE_KEY,   REQUESTOR_PUBLIC_KEY)
deserialized_task_to_compute    = load(serialized_task_to_compute,  REQUESTOR_PRIVATE_KEY,  PROVIDER_PUBLIC_KEY, check_time = False)

force_report_computed_task = message.ForceReportComputedTask()
force_report_computed_task.task_to_compute = deserialized_task_to_compute
serialized_force_report_computed_task = dump(force_report_computed_task, PROVIDER_PRIVATE_KEY, CONCENT_PUBLIC_KEY)
serialized_force_report_computed_task = serialized_force_report_computed_task[:120] + b'\x00' + serialized_force_report_computed_task[120:]

load(
    serialized_force_report_computed_task,
    CONCENT_PRIVATE_KEY,
    PROVIDER_PUBLIC_KEY,
)
```

causes

```

~/work/codepoets/golem/venv-concent/src/golem-messages/golem_messages/shortcuts.py in load(data, privkey, pubkey, check_time)
     36         )
     37 
---> 38     msg = base.Message.deserialize(data, decrypt, check_time, verify)
     39     return msg

~/work/codepoets/golem/venv-concent/src/golem-messages/golem_messages/message/base.py in deserialize(cls, msg, decrypt_func, check_time, verify_func)
    268         header = cls.deserialize_header(raw_header)
    269         if header.encrypted:
--> 270             data = decrypt_func(data)
    271         slots = serializer.loads(data)
    272 

~/work/codepoets/golem/venv-concent/src/golem-messages/golem_messages/shortcuts.py in decrypt(payload)
     25             return payload
     26         ecc = cryptography.ECCx(privkey)
---> 27         return ecc.decrypt(payload)
     28 
     29     def verify(msg_hash, signature):

~/work/codepoets/golem/venv-concent/src/golem-messages/golem_messages/cryptography.py in ecies_decrypt(self, data, shared_mac_data)
    290 
    291         key_material = self.raw_get_ecdh_key(
--> 292             pubkey_x=_shared[:32], pubkey_y=_shared[32:]
    293         )
    294         assert len(key_material) == 32

~/work/codepoets/golem/venv-concent/lib/python3.6/site-packages/pyelliptic-1.5.7-py3.6.egg/pyelliptic/ecc.py in raw_get_ecdh_key(self, pubkey_x, pubkey_y)
    322             OpenSSL.BN_free(other_pub_key_y)
    323             OpenSSL.EC_POINT_free(other_pub_key)
--> 324             OpenSSL.EC_KEY_free(own_key)
    325             OpenSSL.BN_free(own_priv_key)
    326 

UnboundLocalError: local variable 'own_key' referenced before assignment
```

**Comment by cameel** [comment] 2018-02-01 22:57
Looks like a duplicate of #114.

**Closed** 2018-02-02 11:34 UTC
Labels: in progress
